from pathlib import Path

p = Path("backend/server.js")
s = p.read_text(encoding="utf-8")

block = r'''

app.post("/admin/auto-research", async (req, res) => {
  try {
    const datasets = readDatasets();

    const trustedSources = [
      {
        name: "Global Cancer Observatory - IARC / GLOBOCAN",
        url: "https://gco.iarc.who.int/",
        scope: "Global cancer incidence and mortality indicators",
        status: "candidate_source"
      },
      {
        name: "European Cancer Information System - ECIS",
        url: "https://ecis.jrc.ec.europa.eu/data-explorer",
        scope: "European cancer incidence, mortality, survival and projections",
        status: "candidate_source"
      },
      {
        name: "WHO Cancer Data",
        url: "https://www.who.int/health-topics/cancer",
        scope: "Cancer public health indicators and references",
        status: "candidate_source"
      }
    ];

    const now = new Date().toISOString();

    const generatedRows = [
      {
        Bolge: "Avrupa",
        Ulke_Sehir: "Germany",
        Cinsiyet: "All",
        Kanser_Turu: "All cancers",
        Yas_Grubu: "All ages",
        Yillik_Vaka_Hizi_100Bin: "AUTO_REVIEW_REQUIRED",
        Yillik_Olum_Hizi_100Bin: "AUTO_REVIEW_REQUIRED",
        Bes_Yillik_Sagkalim_Yuzdesi: "AUTO_REVIEW_REQUIRED",
        Source: "ECIS / IARC candidate",
        Auto_Research_Timestamp: now
      },
      {
        Bolge: "Global",
        Ulke_Sehir: "Global reference",
        Cinsiyet: "All",
        Kanser_Turu: "All cancers",
        Yas_Grubu: "All ages",
        Yillik_Vaka_Hizi_100Bin: "AUTO_REVIEW_REQUIRED",
        Yillik_Olum_Hizi_100Bin: "AUTO_REVIEW_REQUIRED",
        Bes_Yillik_Sagkalim_Yuzdesi: "AUTO_REVIEW_REQUIRED",
        Source: "GLOBOCAN candidate",
        Auto_Research_Timestamp: now
      }
    ];

    const autoDataset = {
      id: `auto_${Date.now()}`,
      name: `auto_research_candidates_${Date.now()}.csv`,
      originalName: "Auto Research Candidate Sources",
      uploadedAt: now,
      rowCount: generatedRows.length,
      published: false,
      qualityFlag: "needs_verification",
      sourceName: "Auto Research Agent",
      sourceUrl: "https://gco.iarc.who.int/ | https://ecis.jrc.ec.europa.eu/data-explorer",
      automationStatus: "draft_generated",
      automationNote:
        "This dataset was generated by the Auto Research Agent. Values require admin validation before publishing.",
      discoveredSources: trustedSources,
      rows: generatedRows
    };

    datasets.unshift(autoDataset);
    writeDatasets(datasets);

    res.json({
      success: true,
      message: "Auto research completed. Draft dataset generated for admin review.",
      dataset: autoDataset,
      sources: trustedSources
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      error: "Auto research failed",
      detail: err.message
    });
  }
});

'''

if 'app.post("/admin/auto-research"' in s:
    print("ℹ️ Auto research endpoint already exists.")
else:
    idx = s.rfind("app.listen")
    if idx == -1:
        raise SystemExit("❌ app.listen bulunamadı.")

    s = s[:idx] + block + "\n" + s[idx:]
    p.write_text(s, encoding="utf-8")
    print("✅ Auto research endpoint added before app.listen.")
